### ISSUE TITLE
Error build

### ISSUE THREAD

**Issue by AllStrategy-Furlan** [chaudharypraveen98/Simple-React-Native-Push-Notification#1]
Hi i have one error, do you have solution ? 
Error: https://pastebin.com/7anAbXtQ
Thanks

**Comment by chaudharypraveen98** [comment]
Have you changed anything in file related to package name com.simplefirebasenotification

Are you following the readme to create your own project or just cloning the code?

**Comment by AllStrategy-Furlan** [comment]
Hello, I did all the exchange as you guided, but I still have the error:
https://pastebin.com/zjxfdUEX
Do you have solution ?

**Comment by chaudharypraveen98** [comment]
Got your problem , Actually your emulator device memory is full, There are two option available

1. Clear the cache from the device
2. Increase the memory size

Please refer this https://stackoverflow.com/questions/62861072/install-failed-insufficient-storage-error-when-i-ran-npm-run-android-command

If you still find issue , 
Could you please check package version once

    "@react-native-firebase/app": "^15.6.0",
    "@react-native-firebase/messaging": "^15.6.0",
    "react": "18.1.0",
    "react-native": "0.70.1",
    "react-native-mmkv": "^2.4.3"

**Comment by AllStrategy-Furlan** [comment]
Hi, its work, but i have new problem:
https://pastebin.com/NZ5GVmSF
whats solution ?
Observation: file google-services.json exist in android/app
thanks

**Comment by chaudharypraveen98** [comment]
Actually you are using a emulator which lacks Google Play services... Use emulator which has Google Play...or test via adb on real device.

**Comment by AllStrategy-Furlan** [comment]
My friend was the same, thank you very much
